### ISSUE TITLE
Nuxt plugin breaks theme

### ISSUE THREAD

**Issue by snelg** [yariksav/vuetify-dialog#107] opened 2020-10-02 05:10 UTC
This one's much easier to demonstrate than explain:

https://codesandbox.io/s/vuetify-dialog-nuxt-theme-break-lkx7g

An explanation of the problem is in included in the demonstration itself, but here's a slightly longer version.

One of my Nuxt projects includes a "theme switching" feature, where the user can switch to different color palettes while using the site.
In the code, I do this palette change by simply changing the values of `$vuetify.theme.currentTheme.primary`, `$vuetify.theme.currentTheme.secondary`, etc. This method is specifically described in the [Vuetify documentation on dynamic theme customization](https://vuetifyjs.com/en/features/theme/#customizing)

That's been working fine for a while. I added vuetify-dialog to the project, and that works great as well :)
But at some point I realized that after *any* call to `$dialog.*` (e.g. `$dialog.notify.info('Hi!')` ), the palette changing no longer works.

The codesandbox demonstration is a minimal installation of Nuxt + Vuetify + vuetify-dialog that demonstrates the problem.

**Comment by yariksav** [comment] 2020-10-02 14:07
Hi, @snelg 
THank you for sandbox with your issue

I suppose the problem is not with @dialog
You try to change primary, but $dialog.notify.info uses **info** color

Look 
https://codesandbox.io/s/vuetify-dialog-nuxt-theme-break-forked-qbb8i?file=/pages/index.vue

I changed to notify.warning and tried to change warning color - and dialog color changes with the project

**Comment by yariksav** [comment] 2020-10-02 14:30
Can you try to write this issue to vuetify team? Maybe they will help... at least with advice. I suppose problem will be in framework logic, but I don't know for sure how. They know how works framework inside. I see that reactivity works (text color changes)

**Comment by yariksav** [comment] 2020-10-02 14:45
As I investigated vuetify changes own style block in header, and after dialog shows - it stoped to do this

![image](https://user-images.githubusercontent.com/2553313/94936432-e667b200-04d6-11eb-8fde-9ddf34d8e6fa.png)

**Comment by snelg** [comment] 2020-10-02 16:56
I also reached that conclusion.
I just noticed this from the [Vuetify docs](https://vuetifyjs.com/en/components/application/)
"Vuetify doesn’t support multiple isolated Vuetify instances on a page. v-app can exist anywhere inside the body of your app, however, there should only be one and it must be the parent of ALL Vuetify components."

Oh, well.

I do have a hacky workaround: Every time I change a theme color, if I *also* trigger the reactivity of `$vuetify.theme.dark` by setting it to its own current value, then vuetify does rebuild that `<style>` header.

```
$vuetify.theme.dark = $vuetify.theme.dark
```

I prefer clean solutions, but I can live with hacky workarounds when necessary :)

**Comment by yariksav** [comment] 2020-10-02 17:16
Yeah
This hack works because of 
https://github.com/vuetifyjs/vuetify/blob/56f5668d27b6ac0a52c792fb9745164155faa8e3/packages/vuetify/src/services/theme/index.ts#L118

```
  public setTheme (theme: 'light' | 'dark', value: object) {
    this.themes[theme] = Object.assign(this.themes[theme], value)
    --> this.applyTheme()
  }
```
Just target is to call applyTheme() method somehow. 

Maybe then better to call
```
this.$vuetify.application.framework.theme.applyTheme();
```
see https://codesandbox.io/s/vuetify-dialog-nuxt-theme-break-forked-v01yx?file=/pages/index.vue

I close this issue because it cannot be fixed and we have solution

**Closed by yariksav** 2020-10-02 17:16 UTC
